name: simple_date_formatter
description: A simple way of formatting dates
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
  date_time_format: ^2.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
