name: simple_date_formatter
description: A simple way to format dates
version: 1.0.0
homepage: https://github.com/Ejasackey/simple_date_formatter
repository: https://github.com/Ejasackey/simple_date_formatter

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
